---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: yogenyslav/streaming-api:1.0.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999
          volumeMounts:
            - mountPath: /static
              name: static
      volumes:
        - name: static
---
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  ports:
    - name: http
      port: 9999
      targetPort: 9999
  selector:
    app: api
