---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detection
spec:
  replicas: 2
  selector:
    matchLabels:
      app: detection
  template:
    metadata:
      labels:
        app: detection
    spec:
      hostname: detection-service
      containers:
        - name: detection
          image: yogenyslav/streaming-detection:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10001
---
apiVersion: v1
kind: Service
metadata:
  name: detection
spec:
  type: NodePort
  ports:
    - name: http
      port: 10001
      targetPort: 10001
  selector:
    app: detection
