---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frame
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frame
  template:
    metadata:
      labels:
        app: frame
    spec:
      hostname: frame-service
      containers:
        - name: frame
          image: yogenyslav/streaming-frame:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
---
apiVersion: v1
kind: Service
metadata:
  name: frame
spec:
  type: NodePort
  ports:
    - name: http
      port: 10000
      targetPort: 10000
  selector:
    app: frame
