---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      hostname: pg
      containers:
        - env:
            - name: POSTGRES_USER
              value: "pguser"
            - name: POSTGRES_PASSWORD
              value: "pgpass"
            - name: POSTGRES_DB
              value: "dev"
          name: pg
          image: postgres:15
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  type: NodePort
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: pg
