# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frame.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x66rame.proto\x12\tstreaming\"i\n\x05Query\x12\n\n\x02id\x18\x01 \x01(\x03\x12\"\n\x04type\x18\x02 \x01(\x0e\x32\x14.streaming.QueryType\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x14\n\x07timeout\x18\x04 \x01(\x03H\x00\x88\x01\x01\x42\n\n\x08_timeout\"5\n\x08Response\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.streaming.ResponseStatus\"\x1f\n\x0cProcessedReq\x12\x0f\n\x07queryId\x18\x01 \x01(\x03\"\x1c\n\rProcessedResp\x12\x0b\n\x03src\x18\x01 \x03(\t*\x1f\n\tQueryType\x12\x08\n\x04\x46ile\x10\x00\x12\x08\n\x04Link\x10\x01*F\n\x0eResponseStatus\x12\x0b\n\x07Success\x10\x00\x12\x0e\n\nProcessing\x10\x01\x12\t\n\x05\x45rror\x10\x02\x12\x0c\n\x08\x43\x61nceled\x10\x03\x32\x88\x01\n\x0c\x46rameService\x12\x32\n\x07Process\x12\x10.streaming.Query\x1a\x13.streaming.Response\"\x00\x12\x44\n\rFindProcessed\x12\x17.streaming.ProcessedReq\x1a\x18.streaming.ProcessedResp\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frame_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_QUERYTYPE']._serialized_start=251
  _globals['_QUERYTYPE']._serialized_end=282
  _globals['_RESPONSESTATUS']._serialized_start=284
  _globals['_RESPONSESTATUS']._serialized_end=354
  _globals['_QUERY']._serialized_start=26
  _globals['_QUERY']._serialized_end=131
  _globals['_RESPONSE']._serialized_start=133
  _globals['_RESPONSE']._serialized_end=186
  _globals['_PROCESSEDREQ']._serialized_start=188
  _globals['_PROCESSEDREQ']._serialized_end=219
  _globals['_PROCESSEDRESP']._serialized_start=221
  _globals['_PROCESSEDRESP']._serialized_end=249
  _globals['_FRAMESERVICE']._serialized_start=357
  _globals['_FRAMESERVICE']._serialized_end=493
# @@protoc_insertion_point(module_scope)
