# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import frame_pb2 as frame__pb2


class FrameServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Process = channel.unary_unary(
                '/streaming.FrameService/Process',
                request_serializer=frame__pb2.Query.SerializeToString,
                response_deserializer=frame__pb2.Response.FromString,
                )
        self.FindProcessed = channel.unary_unary(
                '/streaming.FrameService/FindProcessed',
                request_serializer=frame__pb2.ProcessedReq.SerializeToString,
                response_deserializer=frame__pb2.ProcessedResp.FromString,
                )


class FrameServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Process(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindProcessed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FrameServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Process': grpc.unary_unary_rpc_method_handler(
                    servicer.Process,
                    request_deserializer=frame__pb2.Query.FromString,
                    response_serializer=frame__pb2.Response.SerializeToString,
            ),
            'FindProcessed': grpc.unary_unary_rpc_method_handler(
                    servicer.FindProcessed,
                    request_deserializer=frame__pb2.ProcessedReq.FromString,
                    response_serializer=frame__pb2.ProcessedResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.FrameService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FrameService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Process(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streaming.FrameService/Process',
            frame__pb2.Query.SerializeToString,
            frame__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindProcessed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/streaming.FrameService/FindProcessed',
            frame__pb2.ProcessedReq.SerializeToString,
            frame__pb2.ProcessedResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
