// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: protos/frame.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrameServiceClient is the client API for FrameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrameServiceClient interface {
	Process(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error)
	FindProcessed(ctx context.Context, in *ProcessedReq, opts ...grpc.CallOption) (*ProcessedResp, error)
}

type frameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFrameServiceClient(cc grpc.ClientConnInterface) FrameServiceClient {
	return &frameServiceClient{cc}
}

func (c *frameServiceClient) Process(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/streaming.FrameService/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *frameServiceClient) FindProcessed(ctx context.Context, in *ProcessedReq, opts ...grpc.CallOption) (*ProcessedResp, error) {
	out := new(ProcessedResp)
	err := c.cc.Invoke(ctx, "/streaming.FrameService/FindProcessed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FrameServiceServer is the server API for FrameService service.
// All implementations must embed UnimplementedFrameServiceServer
// for forward compatibility
type FrameServiceServer interface {
	Process(context.Context, *Query) (*Response, error)
	FindProcessed(context.Context, *ProcessedReq) (*ProcessedResp, error)
	mustEmbedUnimplementedFrameServiceServer()
}

// UnimplementedFrameServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFrameServiceServer struct {
}

func (UnimplementedFrameServiceServer) Process(context.Context, *Query) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedFrameServiceServer) FindProcessed(context.Context, *ProcessedReq) (*ProcessedResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindProcessed not implemented")
}
func (UnimplementedFrameServiceServer) mustEmbedUnimplementedFrameServiceServer() {}

// UnsafeFrameServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrameServiceServer will
// result in compilation errors.
type UnsafeFrameServiceServer interface {
	mustEmbedUnimplementedFrameServiceServer()
}

func RegisterFrameServiceServer(s grpc.ServiceRegistrar, srv FrameServiceServer) {
	s.RegisterService(&FrameService_ServiceDesc, srv)
}

func _FrameService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streaming.FrameService/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameServiceServer).Process(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _FrameService_FindProcessed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessedReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FrameServiceServer).FindProcessed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/streaming.FrameService/FindProcessed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FrameServiceServer).FindProcessed(ctx, req.(*ProcessedReq))
	}
	return interceptor(ctx, in, info, handler)
}

// FrameService_ServiceDesc is the grpc.ServiceDesc for FrameService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FrameService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "streaming.FrameService",
	HandlerType: (*FrameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _FrameService_Process_Handler,
		},
		{
			MethodName: "FindProcessed",
			Handler:    _FrameService_FindProcessed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/frame.proto",
}
