server:
  port: 9999
  logLevel: "debug"
  corsOrigins: "*"

postgres:
  user: "pguser"
  password: "pgpass"
  host: "pg"
  port: 5432
  db: "dev"
  ssl: false

orchestrator:
  host: "orchestrator"
  port: 9988

minio:
  host: "minio:9000"
  accessKey: "access"
  secretKey: "secret"
  ssl: false
  buckets:
    - name: "video"
      region: "eu-west-1"
      lock: true
